<?php

namespace SID\Api\UnityBundle\Repository;

/**
 * UnidadEjecutoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadEjecutoraRepository extends \Doctrine\ORM\EntityRepository
{
}
