<?php

namespace SID\Api\UnityBundle\Repository;

/**
 * UsuarioUnidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioUnidadRepository extends \Doctrine\ORM\EntityRepository
{
}
