services:
#    user.example:
#        class: SID\Api\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    api.users.password_updater:
        class:     SID\Api\UserBundle\Service\PasswordUpdaterService
        arguments: ['@security.encoder_factory']

    api.users.user_listener:
        class:     SID\Api\UserBundle\EventListener\UserListener
        arguments: ['@api.users.password_updater']
        tags:
            - { name: doctrine.event_subscriber }

