client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /

movement:
    resource: "@MovementBundle/Resources/config/routing.yml"
    prefix:   /movimientos

provider:
    resource: "@ProviderBundle/Resources/config/routing.yml"
    prefix:   /proveedores

drug:
    resource: "@DrugBundle/Resources/config/routing.yml"
    prefix:   /drogueros

unity:
    resource: "@UnityBundle/Resources/config/routing.yml"
    prefix:   /unidades

substance:
    resource: "@SubstanceBundle/Resources/config/routing.yml"
    prefix:   /drogas

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /usuarios

