api_login_check:
    path: /api/login_check

movement:
    resource: "@MovementBundle/Resources/config/routing.yml"
    prefix:   /api/movimientos

provider:
    resource: "@ProviderBundle/Resources/config/routing.yml"
    prefix:   /api/proveedores

drug:
    resource: "@DrugBundle/Resources/config/routing.yml"
    prefix:   /api/drogueros

unity:
    resource: "@UnityBundle/Resources/config/routing.yml"
    prefix:   /unidades

substance:
    resource: "@SubstanceBundle/Resources/config/routing.yml"
    prefix:   /api/sustancias

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /api/usuarios

client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /
