api_login_check:
    path: /api/login_check

movement:
    resource: "@MovementBundle/Resources/config/routing.yml"
    prefix:   /movimientos

provider:
    resource: "@ProviderBundle/Resources/config/routing.yml"
    prefix:   /proveedores

drug:
    resource: "@DrugBundle/Resources/config/routing.yml"
    prefix:   /drogueros

unity:
    resource: "@UnityBundle/Resources/config/routing.yml"
    prefix:   /unidades

substance:
    resource: "@SubstanceBundle/Resources/config/routing.yml"
    prefix:   /sustancias

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /usuarios
