client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /

movement:
    resource: "@MovementBundle/Resources/config/routing.yml"
    prefix:   /api/movimientos

provider:
    resource: "@ProviderBundle/Resources/config/routing.yml"
    prefix:   /api/proveedores

drug:
    resource: "@DrugBundle/Resources/config/routing.yml"
    prefix:   /api/drogueros

unity:
    resource: "@UnityBundle/Resources/config/routing.yml"
    prefix:   /api/unidades

substance:
    resource: "@SubstanceBundle/Resources/config/routing.yml"
    prefix:   /api/drogas

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /api/usuarios

