# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        SID\Api\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_db:
            entity: { class: SID\Api\UserBundle\Entity\User, property: username }

    firewalls:
        main:
            pattern:  ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                require_previous_session: false
            logout:
                path: /logout
                target: /
            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios, roles: ROLE_ADMIN }
        - { path: ^/sustancias, roles: ROLE_ADMIN }
        - { path: ^/movimientos, roles: ROLE_ADMIN }
        - { path: ^/unidades, roles: ROLE_ADMIN }
        - { path: ^/drogueros/lugares, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }