<?php

namespace SID\Api\ProviderBundle\Repository;

/**
 * ComprobanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprobanteRepository extends \Doctrine\ORM\EntityRepository
{
}
