motivo_index:
    path:     /
    defaults: { _controller: "MovementBundle:Motivo:index" }
    methods:  GET

motivo_new:
    path:     /
    defaults: { _controller: "MovementBundle:Motivo:new" }
    methods:  POST

motivo_show:
    path:     /{id}
    defaults: { _controller: "MovementBundle:Motivo:show" }
    methods:  GET

motivo_edit:
    path:     /{id}
    defaults: { _controller: "MovementBundle:Motivo:edit" }
    methods:  POST

motivo_delete:
    path:     /{id}
    defaults: { _controller: "MovementBundle:Motivo:delete" }
    methods:  DELETE
