movimiento_index:
    path:     /
    defaults: { _controller: "MovementBundle:Movimiento:index" }
    methods:  GET

movimiento_show:
    path:     /{id}/show
    defaults: { _controller: "MovementBundle:Movimiento:show" }
    methods:  GET

movimiento_new:
    path:     /new
    defaults: { _controller: "MovementBundle:Movimiento:new" }
    methods:  [GET, POST]

movimiento_edit:
    path:     /{id}/edit
    defaults: { _controller: "MovementBundle:Movimiento:edit" }
    methods:  [GET, POST]

movimiento_delete:
    path:     /{id}/delete
    defaults: { _controller: "MovementBundle:Movimiento:delete" }
    methods:  DELETE
