user_index:
    path:     /
    defaults: { _controller: "UserBundle:User:index" }
    methods:  GET

user_new:
    path:     /
    defaults: { _controller: "UserBundle:User:new" }
    methods:  POST

user_show:
    path:     /{id}
    defaults: { _controller: "UserBundle:User:show" }
    methods:  GET

user_edit:
    path:     /{id}
    defaults: { _controller: "UserBundle:User:edit" }
    methods:  POST

user_delete:
    path:     /{id}
    defaults: { _controller: "UserBundle:User:delete" }
    methods:  DELETE
