<?php

namespace SID\Api\DrugBundle\Repository;

/**
 * SubdivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubdivisionRepository extends \Doctrine\ORM\EntityRepository
{
}
