<?php

namespace SID\Api\SubstanceBundle\Repository;

/**
 * ClaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaseRepository extends \Doctrine\ORM\EntityRepository
{
}
