<?php

namespace SID\Api\SubstanceBundle\Repository;

/**
 * ConversionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversionRepository extends \Doctrine\ORM\EntityRepository
{
}
