<?php

namespace SID\Api\SubstanceBundle\Repository;

/**
 * DrogaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrogaRepository extends \Doctrine\ORM\EntityRepository
{
}
