<?php

namespace SID\Api\SubstanceBundle\Repository;

/**
 * SinonimoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SinonimoRepository extends \Doctrine\ORM\EntityRepository
{
}
