<?php

namespace SID\Api\SubstanceBundle\Repository;

/**
 * UnidadMedidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadMedidaRepository extends \Doctrine\ORM\EntityRepository
{
}
