movement_movimiento:
    resource: "@MovementBundle/Resources/config/routing/movimiento.yml"
    prefix:   /movimiento

movement_homepage:
    path:     /
    defaults: { _controller: MovementBundle:Default:index }
