movement_motivos:
    resource: "@MovementBundle/Resources/config/routing/motivo.yml"
    prefix:   /motivos
movement_movimiento:
    resource: "@MovementBundle/Resources/config/routing/movimiento.yml"
    prefix:   /
