tipo_index:
    path:     /
    defaults: { _controller: "UnityBundle:Tipo:index" }
    methods:  GET

tipo_show:
    path:     /{id}
    defaults: { _controller: "UnityBundle:Tipo:show" }
    methods:  GET

tipo_new:
    path:     /
    defaults: { _controller: "UnityBundle:Tipo:new" }
    methods:  POST

tipo_edit:
    path:     /{id}
    defaults: { _controller: "UnityBundle:Tipo:edit" }
    methods:  POST

tipo_delete:
    path:     /{id}
    defaults: { _controller: "UnityBundle:Tipo:delete" }
    methods:  DELETE
