unidadejecutora_index:
    path:     /
    defaults: { _controller: "UnityBundle:UnidadEjecutora:index" }
    methods:  GET

unidadejecutora_show:
    path:     /{id}/show
    defaults: { _controller: "UnityBundle:UnidadEjecutora:show" }
    methods:  GET

unidadejecutora_new:
    path:     /new
    defaults: { _controller: "UnityBundle:UnidadEjecutora:new" }
    methods:  [GET, POST]

unidadejecutora_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnityBundle:UnidadEjecutora:edit" }
    methods:  [GET, POST]

unidadejecutora_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnityBundle:UnidadEjecutora:delete" }
    methods:  DELETE
