unidadejecutora_index:
    path:     /
    defaults: { _controller: "UnityBundle:UnidadEjecutora:index" }
    methods:  GET

unidadejecutora_show:
    path:     /{id}
    defaults: { _controller: "UnityBundle:UnidadEjecutora:show" }
    methods:  GET
    requirements:
        id: '\d+'

unidadejecutora_new:
    path:     /
    defaults: { _controller: "UnityBundle:UnidadEjecutora:new" }
    methods:  POST

unidadejecutora_edit:
    path:     /{id}
    defaults: { _controller: "UnityBundle:UnidadEjecutora:edit" }
    methods:  POST
    requirements:
        id: '\d+'

unidadejecutora_delete:
    path:     /{id}
    defaults: { _controller: "UnityBundle:UnidadEjecutora:delete" }
    methods:  DELETE
    requirements:
        id: '\d+'
