usuariounidad_index:
    path:     /
    defaults: { _controller: "UnityBundle:UsuarioUnidad:index" }
    methods:  GET

usuariounidad_new:
    path:     /
    defaults: { _controller: "UnityBundle:UsuarioUnidad:new" }
    methods:  POST

usuariounidad_show:
    path:     /{id}
    defaults: { _controller: "UnityBundle:UsuarioUnidad:show" }
    methods:  GET

usuariounidad_edit:
    path:     /{id}
    defaults: { _controller: "UnityBundle:UsuarioUnidad:edit" }
    methods:  POST

usuariounidad_delete:
    path:     /{id}
    defaults: { _controller: "UnityBundle:UsuarioUnidad:delete" }
    methods:  DELETE
