usuariounidad_index:
    path:     /
    defaults: { _controller: "UnityBundle:UsuarioUnidad:index" }
    methods:  GET

usuariounidad_show:
    path:     /{id}/show
    defaults: { _controller: "UnityBundle:UsuarioUnidad:show" }
    methods:  GET

usuariounidad_new:
    path:     /new
    defaults: { _controller: "UnityBundle:UsuarioUnidad:new" }
    methods:  [GET, POST]

usuariounidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnityBundle:UsuarioUnidad:edit" }
    methods:  [GET, POST]

usuariounidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnityBundle:UsuarioUnidad:delete" }
    methods:  DELETE
