<?php

namespace SID\Api\MovementBundle\Repository;

/**
 * MovimientoFisicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoFisicoRepository extends \Doctrine\ORM\EntityRepository
{
}
