drug_lugares:
    resource: "@DrugBundle/Resources/config/routing/lugares.yml"
    prefix:   /lugares

drug_drogueros:
    resource: "@DrugBundle/Resources/config/routing/drogueros.yml"
    prefix:   /
