clase_index:
    path:     /
    defaults: { _controller: "SubstanceBundle:Clase:index" }
    methods:  GET

clase_new:
    path:     /
    defaults: { _controller: "SubstanceBundle:Clase:new" }
    methods:  POST

clase_show:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:Clase:show" }
    methods:  GET

clase_edit:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:Clase:edit" }
    methods:  POST

clase_delete:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:Clase:delete" }
    methods:  DELETE
