droga_index:
    path:     /
    defaults: { _controller: "SubstanceBundle:Droga:index" }
    methods:  GET

droga_new:
    path:     /
    defaults: { _controller: "SubstanceBundle:Droga:new" }
    methods:  POST

droga_show:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:Droga:show" }
    methods:  GET

droga_edit:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:Droga:edit" }
    methods:  POST

droga_delete:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:Droga:delete" }
    methods:  DELETE
