entidadreguladora_index:
    path:     /
    defaults: { _controller: "SubstanceBundle:EntidadReguladora:index" }
    methods:  GET

entidadreguladora_new:
    path:     /
    defaults: { _controller: "SubstanceBundle:EntidadReguladora:new" }
    methods:  POST

entidadreguladora_show:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:EntidadReguladora:show" }
    methods:  GET

entidadreguladora_edit:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:EntidadReguladora:edit" }
    methods:  POST

entidadreguladora_delete:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:EntidadReguladora:delete" }
    methods:  DELETE
