ghs_index:
    path:     /
    defaults: { _controller: "SubstanceBundle:GHS:index" }
    methods:  GET

ghs_new:
    path:     /
    defaults: { _controller: "SubstanceBundle:GHS:new" }
    methods:  POST

ghs_show:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:GHS:show" }
    methods:  GET

ghs_edit:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:GHS:edit" }
    methods:  POST

ghs_delete:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:GHS:delete" }
    methods:  DELETE
