sinonimo_index:
    path:     /
    defaults: { _controller: "SubstanceBundle:Sinonimo:index" }
    methods:  GET

sinonimo_new:
    path:     /
    defaults: { _controller: "SubstanceBundle:Sinonimo:new" }
    methods:  POST

sinonimo_show:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:Sinonimo:show" }
    methods:  GET

sinonimo_edit:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:Sinonimo:edit" }
    methods:  POST

sinonimo_delete:
    path:     /{id}
    defaults: { _controller: "SubstanceBundle:Sinonimo:delete" }
    methods:  DELETE
