droguerounidad_index:
    path:     /
    defaults: { _controller: "DrugBundle:DrogueroUnidad:index" }
    methods:  GET

droguerounidad_show:
    path:     /{id}/show
    defaults: { _controller: "DrugBundle:DrogueroUnidad:show" }
    methods:  GET

droguerounidad_new:
    path:     /new
    defaults: { _controller: "DrugBundle:DrogueroUnidad:new" }
    methods:  [GET, POST]

droguerounidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "DrugBundle:DrogueroUnidad:edit" }
    methods:  [GET, POST]

droguerounidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "DrugBundle:DrogueroUnidad:delete" }
    methods:  DELETE
