droguero_index:
    path:     /
    defaults: { _controller: "DrugBundle:Droguero:index" }
    methods:  GET

droguero_new:
    path:     /
    defaults: { _controller: "DrugBundle:Droguero:new" }
    methods:  POST

drouero_divisiones_new:
    path: /divisiones/
    defaults: { _controller: "DrugBundle:Division:new" }
    methods:  POST

drouero_division_show:
    path: /divisiones/{id}
    defaults: { _controller: "DrugBundle:Division:show" }
    methods:  GET


droguero_users:
    path:     /{id}/usuarios/
    defaults: { _controller: "DrugBundle:Droguero:users" }
    methods:  GET

droguero_grant:
    path:     /{id}/usuarios/
    defaults: { _controller: "DrugBundle:Droguero:grant" }
    methods:  POST

droguero_revoke:
    path:     /{id}/usuarios/
    defaults: { _controller: "DrugBundle:Droguero:revoke" }
    methods:  DELETE

droguero_show:
    path:     /{id}
    defaults: { _controller: "DrugBundle:Droguero:show" }
    methods:  GET

droguero_edit:
    path:     /{id}
    defaults: { _controller: "DrugBundle:Droguero:edit" }
    methods:  POST

droguero_delete:
    path:     /{id}
    defaults: { _controller: "DrugBundle:Droguero:delete" }
    methods:  DELETE