droguero_index:
    path:     /
    defaults: { _controller: "DrugBundle:Droguero:index" }
    methods:  GET

droguero_new:
    path:     /
    defaults: { _controller: "DrugBundle:Droguero:new" }
    methods:  POST

droguero_show:
    path:     /{id}
    defaults: { _controller: "DrugBundle:Droguero:show" }
    methods:  GET

droguero_edit:
    path:     /{id}
    defaults: { _controller: "DrugBundle:Droguero:edit" }
    methods:  POST

droguero_delete:
    path:     /{id}
    defaults: { _controller: "DrugBundle:Droguero:delete" }
    methods:  DELETE
