stock_index:
    path:     /
    defaults: { _controller: "DrugBundle:Stock:index" }
    methods:  GET

stock_show:
    path:     /{id}/show
    defaults: { _controller: "DrugBundle:Stock:show" }
    methods:  GET

stock_new:
    path:     /new
    defaults: { _controller: "DrugBundle:Stock:new" }
    methods:  [GET, POST]

stock_edit:
    path:     /{id}/edit
    defaults: { _controller: "DrugBundle:Stock:edit" }
    methods:  [GET, POST]

stock_delete:
    path:     /{id}/delete
    defaults: { _controller: "DrugBundle:Stock:delete" }
    methods:  DELETE
