substance_clase:
    resource: "@SubstanceBundle/Resources/config/routing/clase.yml"
    prefix:   /clases
substance_entidades:
    resource: "@SubstanceBundle/Resources/config/routing/entidadreguladora.yml"
    prefix:   /entidades
substance_ghs:
    resource: "@SubstanceBundle/Resources/config/routing/ghs.yml"
    prefix:   /ghs
substance_sinonimos:
    resource: "@SubstanceBundle/Resources/config/routing/sinonimo.yml"
    prefix:   /sinonimos
substance_droga:
    resource: "@SubstanceBundle/Resources/config/routing/droga.yml"
    prefix:   /
